### ISSUE TITLE
Android emulator detectVPN always false.

### ISSUE THREAD

**Issue by wmfeuvrel** [kzlsnn/react-native-vpn-detect#1]
Hi, 
Having completed the modules installation steps, when using an Android emulator,  the call to detectVPN() always returns false.  On the iOS simulator, the response is true. Is this to be expected?  

Does the module detect the VPN connectivity on the host system?  

Thanks!

**Comment by kzlsnn** [comment]
Hi, are you using the latest version?

**Comment by wmfeuvrel** [comment]
Yes, 1.0.8.  Here's the code block.

![image](https://user-images.githubusercontent.com/2787040/163395970-c6769372-09c3-4a07-891d-708176785951.png)

**Comment by kzlsnn** [comment]
Got it, can you try to write the code async?

**Comment by wmfeuvrel** [comment]
No change. 
![image](https://user-images.githubusercontent.com/2787040/163400903-36c1885d-6ace-4af2-b726-9b90b92c77a8.png)

**Comment by kzlsnn** [comment]
I updated the library, can you install the new version and check again?

**Comment by kzlsnn** [comment]
You have opened vpn on the computer you are using and you want to detect it in your application on the android emulator, is it true?

**Comment by wmfeuvrel** [comment]
yes, as well as on a real device.

**Comment by kzlsnn** [comment]
Unfortunately, you cannot do this. You can detect the VPN opened on the android device you are using.

**Comment by wmfeuvrel** [comment]
Curiously, it appears that the iOS build it is actually detecting if the host is connected to the VPN. Thank you for being so responsive!
